/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppIntelligenceRouteImport } from './routes/_app.intelligence'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRiskRouteImport } from './routes/_app.risk'
import { Route as AppWatchlistRouteImport } from './routes/_app.watchlist'
import { Route as AppHoldingsIdRouteImport } from './routes/_app.holdings.$id'
import { Route as AppPortfoliosIndexRouteImport } from './routes/_app.portfolios.index'
import { Route as AppPortfoliosIdRouteImport } from './routes/_app.portfolios.$id'
import { Route as AppStocksIndexRouteImport } from './routes/_app.stocks.index'
import { Route as AppStocksSymbolRouteImport } from './routes/_app.stocks.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelligenceRoute = AppIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppWatchlistRoute = AppWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AppRoute,
} as any)
const AppHoldingsIdRoute = AppHoldingsIdRouteImport.update({
  id: '/holdings/$id',
  path: '/holdings/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfoliosIndexRoute = AppPortfoliosIndexRouteImport.update({
  id: '/portfolios/',
  path: '/portfolios/',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfoliosIdRoute = AppPortfoliosIdRouteImport.update({
  id: '/portfolios/$id',
  path: '/portfolios/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStocksIndexRoute = AppStocksIndexRouteImport.update({
  id: '/stocks/',
  path: '/stocks/',
  getParentRoute: () => AppRoute,
} as any)
const AppStocksSymbolRoute = AppStocksSymbolRouteImport.update({
  id: '/stocks/$symbol',
  path: '/stocks/$symbol',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/profile': typeof AppProfileRoute
  '/risk': typeof AppRiskRoute
  '/watchlist': typeof AppWatchlistRoute
  '/holdings/$id': typeof AppHoldingsIdRoute
  '/portfolios/$id': typeof AppPortfoliosIdRoute
  '/stocks/$symbol': typeof AppStocksSymbolRoute
  '/portfolios/': typeof AppPortfoliosIndexRoute
  '/stocks/': typeof AppStocksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/profile': typeof AppProfileRoute
  '/risk': typeof AppRiskRoute
  '/watchlist': typeof AppWatchlistRoute
  '/holdings/$id': typeof AppHoldingsIdRoute
  '/portfolios/$id': typeof AppPortfoliosIdRoute
  '/stocks/$symbol': typeof AppStocksSymbolRoute
  '/portfolios': typeof AppPortfoliosIndexRoute
  '/stocks': typeof AppStocksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/intelligence': typeof AppIntelligenceRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/risk': typeof AppRiskRoute
  '/_app/watchlist': typeof AppWatchlistRoute
  '/_app/holdings/$id': typeof AppHoldingsIdRoute
  '/_app/portfolios/$id': typeof AppPortfoliosIdRoute
  '/_app/stocks/$symbol': typeof AppStocksSymbolRoute
  '/_app/portfolios/': typeof AppPortfoliosIndexRoute
  '/_app/stocks/': typeof AppStocksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/alerts'
    | '/dashboard'
    | '/intelligence'
    | '/profile'
    | '/risk'
    | '/watchlist'
    | '/holdings/$id'
    | '/portfolios/$id'
    | '/stocks/$symbol'
    | '/portfolios/'
    | '/stocks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/alerts'
    | '/dashboard'
    | '/intelligence'
    | '/profile'
    | '/risk'
    | '/watchlist'
    | '/holdings/$id'
    | '/portfolios/$id'
    | '/stocks/$symbol'
    | '/portfolios'
    | '/stocks'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/admin'
    | '/_app/alerts'
    | '/_app/dashboard'
    | '/_app/intelligence'
    | '/_app/profile'
    | '/_app/risk'
    | '/_app/watchlist'
    | '/_app/holdings/$id'
    | '/_app/portfolios/$id'
    | '/_app/stocks/$symbol'
    | '/_app/portfolios/'
    | '/_app/stocks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intelligence': {
      id: '/_app/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AppIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk': {
      id: '/_app/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/watchlist': {
      id: '/_app/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppWatchlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/holdings/$id': {
      id: '/_app/holdings/$id'
      path: '/holdings/$id'
      fullPath: '/holdings/$id'
      preLoaderRoute: typeof AppHoldingsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolios/': {
      id: '/_app/portfolios/'
      path: '/portfolios'
      fullPath: '/portfolios/'
      preLoaderRoute: typeof AppPortfoliosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolios/$id': {
      id: '/_app/portfolios/$id'
      path: '/portfolios/$id'
      fullPath: '/portfolios/$id'
      preLoaderRoute: typeof AppPortfoliosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stocks/': {
      id: '/_app/stocks/'
      path: '/stocks'
      fullPath: '/stocks/'
      preLoaderRoute: typeof AppStocksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stocks/$symbol': {
      id: '/_app/stocks/$symbol'
      path: '/stocks/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof AppStocksSymbolRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIntelligenceRoute: typeof AppIntelligenceRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRiskRoute: typeof AppRiskRoute
  AppWatchlistRoute: typeof AppWatchlistRoute
  AppHoldingsIdRoute: typeof AppHoldingsIdRoute
  AppPortfoliosIdRoute: typeof AppPortfoliosIdRoute
  AppStocksSymbolRoute: typeof AppStocksSymbolRoute
  AppPortfoliosIndexRoute: typeof AppPortfoliosIndexRoute
  AppStocksIndexRoute: typeof AppStocksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIntelligenceRoute: AppIntelligenceRoute,
  AppProfileRoute: AppProfileRoute,
  AppRiskRoute: AppRiskRoute,
  AppWatchlistRoute: AppWatchlistRoute,
  AppHoldingsIdRoute: AppHoldingsIdRoute,
  AppPortfoliosIdRoute: AppPortfoliosIdRoute,
  AppStocksSymbolRoute: AppStocksSymbolRoute,
  AppPortfoliosIndexRoute: AppPortfoliosIndexRoute,
  AppStocksIndexRoute: AppStocksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
